-- Очистка таблиц в правильном порядке
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post_tag;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS tag;

-- Таблица постов
CREATE TABLE IF NOT EXISTS post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    text TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0 NOT NULL,
    comments_count INTEGER DEFAULT 0 NOT NULL,
    image_url VARCHAR(500),
    image_name VARCHAR(255),
    image_size INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE post IS 'Таблица для хранения постов блога. Содержит основную информацию о посте включая заголовок, текст, метаданные и ссылку на изображение';
COMMENT ON COLUMN post.id IS 'Уникальный идентификатор поста, автоинкремент';
COMMENT ON COLUMN post.title IS 'Заголовок поста, обязательное поле, максимальная длина 500 символов';
COMMENT ON COLUMN post.text IS 'Текст поста в формате Markdown, обязательное поле';
COMMENT ON COLUMN post.likes_count IS 'Количество лайков поста, по умолчанию 0';
COMMENT ON COLUMN post.comments_count IS 'Количество комментариев к посту, по умолчанию 0';
COMMENT ON COLUMN post.image_url IS 'URL или путь к файлу изображения поста, опционально';
COMMENT ON COLUMN post.image_name IS 'Оригинальное имя файла изображения для отображения пользователю';
COMMENT ON COLUMN post.image_size IS 'Размер файла изображения в байтах, опционально';
COMMENT ON COLUMN post.created_at IS 'Дата и время создания поста, устанавливается автоматически';
COMMENT ON COLUMN post.updated_at IS 'Дата и время последнего обновления поста, обновляется автоматически';

-- Таблица тегов
CREATE TABLE IF NOT EXISTS tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

COMMENT ON TABLE tag IS 'Таблица для хранения уникальных тегов, которые могут быть присвоены постам';
COMMENT ON COLUMN tag.id IS 'Уникальный идентификатор тега, автоинкремент';
COMMENT ON COLUMN tag.name IS 'Уникальное название тега, используется для группировки и поиска постов';

-- Таблица связи постов и тегов
CREATE TABLE IF NOT EXISTS post_tag (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE CASCADE
);

COMMENT ON TABLE post_tag IS 'Таблица связи многие-ко-многим между постами и тегами. Один пост может иметь несколько тегов, один тег может принадлежать нескольким постам';
COMMENT ON COLUMN post_tag.post_id IS 'Внешний ключ на таблицу post, идентификатор поста';
COMMENT ON COLUMN post_tag.tag_id IS 'Внешний ключ на таблицу tag, идентификатор тега';

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE
);

COMMENT ON TABLE comment IS 'Таблица для хранения комментариев к постам. Каждый комментарий принадлежит одному посту';
COMMENT ON COLUMN comment.id IS 'Уникальный идентификатор комментария, автоинкремент';
COMMENT ON COLUMN comment.post_id IS 'Внешний ключ на таблицу post, идентификатор поста к которому относится комментарий';
COMMENT ON COLUMN comment.text IS 'Текст комментария, обязательное поле';
COMMENT ON COLUMN comment.created_at IS 'Дата и время создания комментария, устанавливается автоматически';
COMMENT ON COLUMN comment.updated_at IS 'Дата и время последнего обновления комментария, обновляется при редактировании';

-- Индексы
CREATE INDEX idx_post_title ON post(title);
CREATE INDEX idx_comment_post_id ON comment(post_id);
CREATE INDEX idx_post_tag_post_id ON post_tag(post_id);
CREATE INDEX idx_post_tag_tag_id ON post_tag(tag_id);
CREATE INDEX idx_tag_name ON tag(name);
